### ISSUE TITLE
Laravel 5.1 support ?

### ISSUE THREAD

**Issue by tortuetorche** [rodrigopedra/russian-doll-caching#1]
Hi Rodrigo,

I see in your `composer.json` that we need Laravel >= 5.2 to use your package.
Is there any particular reason for this version constraint?
Can you also support Laravel 5.1 (which is a LTS release)?

Cheers,
Tortue Torche

**Comment by rodrigopedra** [comment]
Hi, thanks for the tip, as 5.1 is a LTS release there is no good reason to not support it.

I changed the composer file, as apparently there was nothing to change.

I checked the Cache, View and Blade Compiler source code, but I can't test it right now, once I test it I'll close the issue.

**Comment by tortuetorche** [comment]
Cool :+1: 

Have a good day!

**Comment by rodrigopedra** [comment]
Tested and fixed
